### PR TITLE
Fixes a remove className bug

### PR DESCRIPTION
**Pull request by mellonis**

### CODE REVIEW

**Comment by tobua** [comment]
Hi @mellonis thanks for the pull request. Unfortunately, this reintroduces a recently fixed bug where remove only removed the first occurrence of a class.

What bug are you trying to solve?

**Comment by mellonis** [comment]
In the IE 11 browser the remove method didn't remove the provided class name at all.

For instance, for the class name `qq` will be generated the following string `(\\s|^)[qq|\\sqq]+(\\s|$)` as the first parameter for the RegEx constructor.

Literally it means: space symbol or the beginning of the string, then `q`, `|`, `\` or `s` (space) (one or several mentioned symbols) and space or the end of the string.

So I think that regular expressions generated in this manner is totally wrong. Or it can work for class names of one character length.

Can you provide some information about your case.

**Comment by mellonis** [comment]
I've made another commit, could you check it?

**Comment by mellonis** [comment]
Here an example https://regex101.com/r/4eViUK/1

**Review by tobua — APPROVED** [review]

**Comment by tobua** [comment]
My case with multiple occurrences of the same class now works fine with your new regex.

The issue with the existing regex was that className wasn't escaped and so failed if special chars like the '-' in your example were used.

Merging the changes because your new regex is much simpler, avoids duplicating className and the need for escaping. Will add some tests with special characters and soon release the fix.

Thanks for the help!

**Pull request merged**
